# Generated by Django 5.1.4 on 2025-01-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Abonamente',
            fields=[
                ('id_abonament', models.AutoField(primary_key=True, serialize=False)),
                ('nume_abonament', models.CharField(blank=True, max_length=100, null=True)),
                ('pret', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valabilitate', models.IntegerField(blank=True, null=True)),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abonamente',
            },
        ),
        migrations.CreateModel(
            name='Angajati',
            fields=[
                ('id_angajat', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(blank=True, max_length=100, null=True)),
                ('prenume', models.CharField(blank=True, max_length=100, null=True)),
                ('functie', models.CharField(blank=True, max_length=50, null=True)),
                ('data_angajarii', models.DateField(blank=True, null=True)),
                ('salariu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('parola', models.CharField(max_length=128, blank=False, null=False)),
            ],
            options={
                'db_table': 'angajati',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clasa', models.AutoField(primary_key=True, serialize=False)),
                ('nume_clasa', models.CharField(blank=True, max_length=100, null=True)),
                ('capacitate_clasa', models.IntegerField(blank=True, null=True)),
                ('ora_incepere', models.TimeField(blank=True, null=True)),
                ('ora_inchidere', models.TimeField(blank=True, null=True)),
                ('data_clasa', models.DateField(blank=True, null=True)),
                ('id_antrenor', models.ForeignKey(blank=True, db_column='id_antrenor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.angajati')),
            ],
            options={
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(blank=True, max_length=100, null=True)),
                ('prenume', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('adresa', models.TextField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('data_inscrierii', models.DateField(blank=True, null=True)),
                ('parola', models.CharField(max_length=128, blank=False, null=False)),
            ],
            options={
                'db_table': 'clienti',
            },
        ),
        migrations.CreateModel(
            name='SaliFitness',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nume_sala', models.CharField(blank=True, max_length=100, null=True)),
                ('adresa', models.TextField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('oras', models.CharField(blank=True, max_length=50, null=True)),
                ('capacitate_sala', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sali_fitness',
            },
        ),
        migrations.CreateModel(
            name='AbonamenteClienti',
            fields=[
                ('id_abonament_client', models.AutoField(primary_key=True, serialize=False)),
                ('data_incepere', models.DateField(blank=True, null=True)),
                ('id_abonament', models.ForeignKey(blank=True, db_column='id_abonament', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.abonamente')),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.clienti')),
            ],
            options={
                'db_table': 'abonamente_clienti',
            },
        ),
        migrations.CreateModel(
            name='Plati',
            fields=[
                ('id_plata', models.AutoField(primary_key=True, serialize=False)),
                ('suma', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_platii', models.DateField(blank=True, null=True)),
                ('id_abonament', models.ForeignKey(blank=True, db_column='id_abonament', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.abonamente')),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.clienti')),
            ],
            options={
                'db_table': 'plati',
            },
        ),
        migrations.CreateModel(
            name='RezervariClase',
            fields=[
                ('id_rezervare', models.AutoField(primary_key=True, serialize=False)),
                ('data_rezervare', models.DateField()),
                ('id_clasa', models.ForeignKey(blank=True, db_column='id_clasa', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.clase')),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.clienti')),
            ],
            options={
                'db_table': 'rezervari_clase',
            },
        ),
        migrations.CreateModel(
            name='IntrariClientiSali',
            fields=[
                ('id_intrare', models.AutoField(primary_key=True, serialize=False)),
                ('data_intrare', models.DateField(blank=True, null=True)),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.clienti')),
                ('id_sala', models.ForeignKey(blank=True, db_column='id_sala', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.salifitness')),
            ],
            options={
                'db_table': 'intrari_clienti_sali',
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='id_sala',
            field=models.ForeignKey(blank=True, db_column='id_sala', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.salifitness'),
        ),
        migrations.CreateModel(
            name='AbonamenteSali',
            fields=[
                ('id_abonament', models.OneToOneField(db_column='id_abonament', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gym.abonamente')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='gym.salifitness')),
            ],
            options={
                'db_table': 'abonamente_sali',
                'unique_together': {('id_abonament', 'id_sala')},
            },
        ),
        migrations.CreateModel(
            name='AngajatiSali',
            fields=[
                ('id_angajat', models.OneToOneField(db_column='id_angajat', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gym.angajati')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, to='gym.salifitness')),
            ],
            options={
                'db_table': 'angajati_sali',
                'unique_together': {('id_angajat', 'id_sala')},
            },
        ),
        migrations.CreateModel(
            name='ParticipareClase',
            fields=[
                ('id_clasa', models.OneToOneField(db_column='id_clasa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gym.clase')),
                ('data_participare', models.DateField()),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='gym.clienti')),
            ],
            options={
                'db_table': 'participare_clase',
                'unique_together': {('id_clasa', 'id_client', 'data_participare')},
            },
        ),
    ]
